FROM golang:1.25.5-alpine AS builder

WORKDIR /service

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY notifications_service .

RUN go build -o notifications_service ./notifications_service